server:
  port: ${SERVER_PORT:8084}

spring:
  rabbitmq:
    host: 10.0.12.184
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
  application:
    name: ms-historial
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    url: jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres
    username: postgres.geijpkyhyeguxhsoynvv
    password: frMQ_-FQyG9J5Ep
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 10000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://internal-bomberos-internal-alb-1797992975.us-east-1.elb.amazonaws.com:8761/eureka/}
  instance:
    prefer-ip-address: false
    hostname: ${HOSTNAME}
    instance-id: ${HOSTNAME}:${spring.application.name}:${random.uuid}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always