server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: ms-monitoreo
  cloud:
    compatibility-verifier:
      enabled: false
    # Obligamos a usar la red privada de AWS (VPC)
    inetutils:
      preferred-networks:
        - 10.0
  datasource:
    url: jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres
    username: postgres.geijpkyhyeguxhsoynvv
    password: frMQ_-FQyG9J5Ep
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 10000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://internal-bomberos-internal-alb-1797992975.us-east-1.elb.amazonaws.com:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always