name: CI/CD Backend Microservices - Bomberos

on: [push]

jobs:
  build-and-push:
    name: Construir y Subir Microservicios a ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Construir y Subir Imágenes Docker
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          SERVICIOS=("eureka-server" "api-gateway" "usuarios" "alertas" "historial" "monitoreo" "reportes")
          
          for SERVICE in "${SERVICIOS[@]}"; do
            echo "--------------------------------------------------"
            echo "Procesando Microservicio: $SERVICE"
            echo "--------------------------------------------------"
          
            cd $SERVICE
          
            docker build -t $ECR_REGISTRY/$SERVICE:latest .
            docker push $ECR_REGISTRY/$SERVICE:latest
          
            cd ..
          done